#
# Copyright (c) 2012-2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
{{- define "jaegerHost" }}
{{- printf "jaeger-%s.%s" .Release.Namespace .Values.global.ingressDomain }}
{{- end }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger-query
{{- if .Values.global.ingressAnnotations }}
  annotations:
{{ toYaml .Values.global.ingressAnnotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - {{ template "jaegerHost" . }}
{{- if .Values.global.tls.secretName }}
    secretName: {{ .Values.global.tls.secretName }}
{{- end }}
{{- end }}
  rules:
  - host: {{ template "jaegerHost" . }}
    http:
      paths:
        - path: /*
          backend:
              serviceName: jaeger-query
              servicePort: 16686
